"""Regenerate the checked-in menu bitmap using Noto Sans CJK SC (OFL 1.1)."""
import argparse
import hashlib
import math
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--font', type=Path, required=True)
    parser.add_argument('--source', type=Path, default=ROOT/'gam4980/src/app.c')
    parser.add_argument('--output', type=Path, default=ROOT/'gam4980/src/platform/menu_font.h')
    args = parser.parse_args()
    font = ImageFont.truetype(str(args.font), 18)
    chars = sorted(set(args.source.read_text(encoding='utf-8')) | set(map(chr,range(32,127))))
    chars = [c for c in chars if ord(c)>=32 and c not in '\r\n']
    out = ['/* Noto Sans CJK SC rendered glyph subset; OFL 1.1.',
           ' * See assets/licenses/NotoSansCJK-OFL.txt and assets/README.md.',
           ' * Generated by tools/generate_menu_font.py. */',
           '#ifndef H1_MENU_FONT_H', '#define H1_MENU_FONT_H',
           'static const struct { uint32_t code, advance, rows[21]; } menu_glyphs[] = {']
    for char in chars:
        glyph_font = font
        left,top,right,bottom = glyph_font.getbbox(char,anchor='ls')
        origin_x = max(0,-left)
        baseline = 16
        if top+baseline<0 or bottom+baseline>21 or right+origin_x>18:
            raise ValueError(f'Glyph U+{ord(char):04X} does not fit the menu cell')
        advance = math.ceil(glyph_font.getlength(char))+origin_x+1 if ord(char)<128 else 20
        bitmap = Image.new('L',(18,21))
        # A common baseline keeps lowercase and descenders in place. Keep the
        # natural Latin advance so wide letters cannot overlap their neighbors.
        ImageDraw.Draw(bitmap).text((origin_x,baseline),char,font=glyph_font,fill=255,anchor='ls')
        rows = [sum(1<<x for x in range(18) if bitmap.getpixel((x,y))>=96) for y in range(21)]
        out.append('{%d,%d,{%s}},'%(ord(char),advance,','.join('0x%x'%v for v in rows)))
    out += ['};','#define MENU_GLYPH_COUNT (sizeof menu_glyphs/sizeof menu_glyphs[0])','#endif']
    args.output.write_text('\n'.join(out)+'\n',encoding='utf-8')
    print('glyphs',len(chars),'font SHA256',hashlib.sha256(args.font.read_bytes()).hexdigest())

if __name__ == '__main__': main()
